apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

- resourcegroup.yaml
- virtualnetwork.yaml
- subnet.yaml
- aks-cluster.yaml

commonLabels:
app.kubernetes.io/name: simple-aks
app.kubernetes.io/managed-by: crossplane
example: simple-aks

namespace: default
