apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

- resourcegroup.yaml
- virtualnetwork.yaml
- subnet.yaml
- log-analytics-workspace.yaml
- aks-cluster-with-addons.yaml

commonLabels:
app.kubernetes.io/name: aks-with-addons
app.kubernetes.io/managed-by: crossplane
example: aks-with-addons

namespace: default
