apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-system
  namespace: crossplane-system
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - providerconfig.yaml
