apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

- resourcegroup.yaml
- network.yaml
- aks-cluster.yaml

commonLabels:
app.kubernetes.io/name: multi-cluster
app.kubernetes.io/managed-by: crossplane
environment: staging

namespace: default
